
// This file has been generated by the GUI designer. Do not modify.
namespace KalliopeSync.View
{
	public partial class ConnectionDialog
	{
		private global::Gtk.VBox vbox4;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label LabelAccount;
		
		private global::Gtk.TextView TextViewAccount;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label LabelAccountKey;
		
		private global::Gtk.TextView TextViewAccount1;
		
		private global::Gtk.HBox hbox4;
		
		private global::Gtk.Label LabelAccountKey1;
		
		private global::Gtk.TextView TextViewAccount2;
		
		private global::Gtk.HBox hbox5;
		
		private global::Gtk.Label LabelAccountKey2;
		
		private global::Gtk.TextView TextViewAccount3;
		
		private global::Gtk.HBox hbox6;
		
		private global::Gtk.Label LabelAccountKey3;
		
		private global::Gtk.TextView TextViewAccount4;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KalliopeSync.View.ConnectionDialog
			this.Name = "KalliopeSync.View.ConnectionDialog";
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child KalliopeSync.View.ConnectionDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox4 = new global::Gtk.VBox ();
			this.vbox4.Name = "vbox4";
			this.vbox4.Spacing = 6;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.LabelAccount = new global::Gtk.Label ();
			this.LabelAccount.WidthRequest = 150;
			this.LabelAccount.Name = "LabelAccount";
			this.LabelAccount.LabelProp = global::Mono.Unix.Catalog.GetString ("Account");
			this.LabelAccount.Justify = ((global::Gtk.Justification)(2));
			this.hbox2.Add (this.LabelAccount);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.LabelAccount]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.TextViewAccount = new global::Gtk.TextView ();
			this.TextViewAccount.WidthRequest = 250;
			this.TextViewAccount.HeightRequest = 28;
			this.TextViewAccount.CanFocus = true;
			this.TextViewAccount.Name = "TextViewAccount";
			this.TextViewAccount.AcceptsTab = false;
			this.hbox2.Add (this.TextViewAccount);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.TextViewAccount]));
			w3.Position = 1;
			this.vbox4.Add (this.hbox2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox2]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox4.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.LabelAccountKey = new global::Gtk.Label ();
			this.LabelAccountKey.WidthRequest = 150;
			this.LabelAccountKey.Name = "LabelAccountKey";
			this.LabelAccountKey.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Key");
			this.hbox3.Add (this.LabelAccountKey);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.LabelAccountKey]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.TextViewAccount1 = new global::Gtk.TextView ();
			this.TextViewAccount1.WidthRequest = 250;
			this.TextViewAccount1.HeightRequest = 28;
			this.TextViewAccount1.CanFocus = true;
			this.TextViewAccount1.Name = "TextViewAccount1";
			this.TextViewAccount1.AcceptsTab = false;
			this.hbox3.Add (this.TextViewAccount1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.TextViewAccount1]));
			w6.Position = 1;
			this.vbox4.Add (this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.hbox3]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			w1.Add (this.vbox4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox4]));
			w8.Position = 0;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox ();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.LabelAccountKey1 = new global::Gtk.Label ();
			this.LabelAccountKey1.WidthRequest = 150;
			this.LabelAccountKey1.Name = "LabelAccountKey1";
			this.LabelAccountKey1.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Key");
			this.hbox4.Add (this.LabelAccountKey1);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.LabelAccountKey1]));
			w9.Position = 0;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.TextViewAccount2 = new global::Gtk.TextView ();
			this.TextViewAccount2.WidthRequest = 250;
			this.TextViewAccount2.HeightRequest = 28;
			this.TextViewAccount2.CanFocus = true;
			this.TextViewAccount2.Name = "TextViewAccount2";
			this.TextViewAccount2.AcceptsTab = false;
			this.hbox4.Add (this.TextViewAccount2);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox4 [this.TextViewAccount2]));
			w10.Position = 1;
			w1.Add (this.hbox4);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox4]));
			w11.Position = 1;
			w11.Expand = false;
			w11.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox ();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.LabelAccountKey2 = new global::Gtk.Label ();
			this.LabelAccountKey2.WidthRequest = 150;
			this.LabelAccountKey2.Name = "LabelAccountKey2";
			this.LabelAccountKey2.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Key");
			this.hbox5.Add (this.LabelAccountKey2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.LabelAccountKey2]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.TextViewAccount3 = new global::Gtk.TextView ();
			this.TextViewAccount3.WidthRequest = 250;
			this.TextViewAccount3.HeightRequest = 28;
			this.TextViewAccount3.CanFocus = true;
			this.TextViewAccount3.Name = "TextViewAccount3";
			this.TextViewAccount3.AcceptsTab = false;
			this.hbox5.Add (this.TextViewAccount3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.TextViewAccount3]));
			w13.Position = 1;
			w1.Add (this.hbox5);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox5]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox ();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.LabelAccountKey3 = new global::Gtk.Label ();
			this.LabelAccountKey3.WidthRequest = 150;
			this.LabelAccountKey3.Name = "LabelAccountKey3";
			this.LabelAccountKey3.LabelProp = global::Mono.Unix.Catalog.GetString ("Account Key");
			this.hbox6.Add (this.LabelAccountKey3);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.LabelAccountKey3]));
			w15.Position = 0;
			w15.Expand = false;
			w15.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.TextViewAccount4 = new global::Gtk.TextView ();
			this.TextViewAccount4.WidthRequest = 250;
			this.TextViewAccount4.HeightRequest = 28;
			this.TextViewAccount4.CanFocus = true;
			this.TextViewAccount4.Name = "TextViewAccount4";
			this.TextViewAccount4.AcceptsTab = false;
			this.hbox6.Add (this.TextViewAccount4);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.TextViewAccount4]));
			w16.Position = 1;
			w1.Add (this.hbox6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(w1 [this.hbox6]));
			w17.Position = 3;
			w17.Expand = false;
			w17.Fill = false;
			// Internal child KalliopeSync.View.ConnectionDialog.ActionArea
			global::Gtk.HButtonBox w18 = this.ActionArea;
			w18.Name = "dialog1_ActionArea";
			w18.Spacing = 10;
			w18.BorderWidth = ((uint)(5));
			w18.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w19 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w18 [this.buttonCancel]));
			w19.Expand = false;
			w19.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w20 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w18 [this.buttonOk]));
			w20.Position = 1;
			w20.Expand = false;
			w20.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 426;
			this.DefaultHeight = 300;
			this.Show ();
		}
	}
}
