
// This file has been generated by the GUI designer. Do not modify.
namespace KalliopeSync.View
{
	public partial class MainWindow
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action ConnectActionAction;
		
		private global::Gtk.VBox vbox1;
		
		private global::Gtk.MenuBar menubar3;
		
		private global::Gtk.Toolbar toolbar5;
		
		private global::Gtk.HPaned hpaned3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView SyncLocationTreeView;
		
		private global::Gtk.Notebook notebook1;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview4;
		
		private global::Gtk.Label ViewTypePageHeaderLabel;
		
		private global::Gtk.IconView iconview2;
		
		private global::Gtk.Label ViewTypePageHeaderLabel1;
		
		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KalliopeSync.View.MainWindow
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("MainMenuActionGroup");
			this.ConnectActionAction = new global::Gtk.Action ("ConnectActionAction", global::Mono.Unix.Catalog.GetString ("ConnectAction"), null, null);
			this.ConnectActionAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("ConnectAction");
			w1.Add (this.ConnectActionAction, null);
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "KalliopeSync.View.MainWindow";
			this.Title = global::Mono.Unix.Catalog.GetString ("KalliopeMedia - KalliopeSync");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.BorderWidth = ((uint)(3));
			// Container child KalliopeSync.View.MainWindow.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox ();
			this.vbox1.WidthRequest = 0;
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 1;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='menubar3'><menu><menuitem/><menuitem/></menu><menu/></menubar></ui>");
			this.menubar3 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar3")));
			this.menubar3.Name = "menubar3";
			this.vbox1.Add (this.menubar3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar5'><toolitem/></toolbar></ui>");
			this.toolbar5 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar5")));
			this.toolbar5.Name = "toolbar5";
			this.toolbar5.ShowArrow = false;
			this.vbox1.Add (this.toolbar5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.toolbar5]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.hpaned3 = new global::Gtk.HPaned ();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 184;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.SyncLocationTreeView = new global::Gtk.TreeView ();
			this.SyncLocationTreeView.CanFocus = true;
			this.SyncLocationTreeView.Name = "SyncLocationTreeView";
			this.GtkScrolledWindow.Add (this.SyncLocationTreeView);
			this.hpaned3.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned3 [this.GtkScrolledWindow]));
			w5.Resize = false;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.notebook1 = new global::Gtk.Notebook ();
			this.notebook1.CanFocus = true;
			this.notebook1.Name = "notebook1";
			this.notebook1.CurrentPage = 1;
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview4 = new global::Gtk.TreeView ();
			this.treeview4.CanFocus = true;
			this.treeview4.Name = "treeview4";
			this.treeview4.HeadersVisible = false;
			this.GtkScrolledWindow1.Add (this.treeview4);
			this.notebook1.Add (this.GtkScrolledWindow1);
			// Notebook tab
			this.ViewTypePageHeaderLabel = new global::Gtk.Label ();
			this.ViewTypePageHeaderLabel.Name = "ViewTypePageHeaderLabel";
			this.ViewTypePageHeaderLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("List View");
			this.notebook1.SetTabLabel (this.GtkScrolledWindow1, this.ViewTypePageHeaderLabel);
			this.ViewTypePageHeaderLabel.ShowAll ();
			// Container child notebook1.Gtk.Notebook+NotebookChild
			this.iconview2 = new global::Gtk.IconView ();
			this.iconview2.CanFocus = true;
			this.iconview2.Name = "iconview2";
			this.notebook1.Add (this.iconview2);
			global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.notebook1 [this.iconview2]));
			w8.Position = 1;
			// Notebook tab
			this.ViewTypePageHeaderLabel1 = new global::Gtk.Label ();
			this.ViewTypePageHeaderLabel1.Name = "ViewTypePageHeaderLabel1";
			this.ViewTypePageHeaderLabel1.LabelProp = global::Mono.Unix.Catalog.GetString ("Icon View");
			this.notebook1.SetTabLabel (this.iconview2, this.ViewTypePageHeaderLabel1);
			this.ViewTypePageHeaderLabel1.ShowAll ();
			this.hpaned3.Add (this.notebook1);
			this.vbox1.Add (this.hpaned3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.hpaned3]));
			w10.Position = 2;
			// Container child vbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox1.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusbar1]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.vbox1);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 512;
			this.DefaultHeight = 300;
			this.Show ();
			this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
			this.ConnectActionAction.Changed += new global::Gtk.ChangedHandler (this.OnConnectActionActionChanged);
		}
	}
}
