
// This file has been generated by the GUI designer. Do not modify.
namespace KalliopeSync.View
{
	public partial class MainView
	{
		private global::Gtk.UIManager UIManager;
		
		private global::Gtk.Action FileAction;
		
		private global::Gtk.Action ConnectAction;
		
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.MenuBar MainMenubar;
		
		private global::Gtk.Toolbar MainToolbar;
		
		private global::Gtk.HPaned hpaned3;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow;
		
		private global::Gtk.TreeView SyncLocationTreeview;
		
		private global::Gtk.Notebook SyncFolderDetailsNotebook;
		
		private global::Gtk.ScrolledWindow GtkScrolledWindow1;
		
		private global::Gtk.TreeView treeview2;
		
		private global::Gtk.Label label1;
		
		private global::Gtk.IconView FolderContentsPreview;
		
		private global::Gtk.Label label2;
		
		private global::Gtk.Statusbar statusbar1;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget KalliopeSync.View.MainView
			this.UIManager = new global::Gtk.UIManager ();
			global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
			this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
			this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
			w1.Add (this.FileAction, null);
			this.ConnectAction = new global::Gtk.Action ("ConnectAction", global::Mono.Unix.Catalog.GetString ("Connect"), null, null);
			this.ConnectAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Connect");
			w1.Add (this.ConnectAction, "<Primary>c");
			this.UIManager.InsertActionGroup (w1, 0);
			this.AddAccelGroup (this.UIManager.AccelGroup);
			this.Name = "KalliopeSync.View.MainView";
			this.Title = global::Mono.Unix.Catalog.GetString ("MainView");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child KalliopeSync.View.MainView.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><menubar name='MainMenubar'><menu name='FileAction' action='FileAction'><menuitem name='ConnectAction' action='ConnectAction'/></menu></menubar></ui>");
			this.MainMenubar = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/MainMenubar")));
			this.MainMenubar.Name = "MainMenubar";
			this.vbox2.Add (this.MainMenubar);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.MainMenubar]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.UIManager.AddUiFromString ("<ui><toolbar name='MainToolbar'/></ui>");
			this.MainToolbar = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/MainToolbar")));
			this.MainToolbar.Name = "MainToolbar";
			this.MainToolbar.ShowArrow = false;
			this.vbox2.Add (this.MainToolbar);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.MainToolbar]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hpaned3 = new global::Gtk.HPaned ();
			this.hpaned3.CanFocus = true;
			this.hpaned3.Name = "hpaned3";
			this.hpaned3.Position = 314;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.SyncLocationTreeview = new global::Gtk.TreeView ();
			this.SyncLocationTreeview.WidthRequest = 299;
			this.SyncLocationTreeview.CanFocus = true;
			this.SyncLocationTreeview.Name = "SyncLocationTreeview";
			this.GtkScrolledWindow.Add (this.SyncLocationTreeview);
			this.hpaned3.Add (this.GtkScrolledWindow);
			global::Gtk.Paned.PanedChild w5 = ((global::Gtk.Paned.PanedChild)(this.hpaned3 [this.GtkScrolledWindow]));
			w5.Resize = false;
			// Container child hpaned3.Gtk.Paned+PanedChild
			this.SyncFolderDetailsNotebook = new global::Gtk.Notebook ();
			this.SyncFolderDetailsNotebook.CanFocus = true;
			this.SyncFolderDetailsNotebook.Name = "SyncFolderDetailsNotebook";
			this.SyncFolderDetailsNotebook.CurrentPage = 0;
			// Container child SyncFolderDetailsNotebook.Gtk.Notebook+NotebookChild
			this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
			this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
			this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
			this.treeview2 = new global::Gtk.TreeView ();
			this.treeview2.CanFocus = true;
			this.treeview2.Name = "treeview2";
			this.GtkScrolledWindow1.Add (this.treeview2);
			this.SyncFolderDetailsNotebook.Add (this.GtkScrolledWindow1);
			// Notebook tab
			this.label1 = new global::Gtk.Label ();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Details");
			this.SyncFolderDetailsNotebook.SetTabLabel (this.GtkScrolledWindow1, this.label1);
			this.label1.ShowAll ();
			// Container child SyncFolderDetailsNotebook.Gtk.Notebook+NotebookChild
			this.FolderContentsPreview = new global::Gtk.IconView ();
			this.FolderContentsPreview.CanFocus = true;
			this.FolderContentsPreview.Name = "FolderContentsPreview";
			this.SyncFolderDetailsNotebook.Add (this.FolderContentsPreview);
			global::Gtk.Notebook.NotebookChild w8 = ((global::Gtk.Notebook.NotebookChild)(this.SyncFolderDetailsNotebook [this.FolderContentsPreview]));
			w8.Position = 1;
			// Notebook tab
			this.label2 = new global::Gtk.Label ();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Preview");
			this.SyncFolderDetailsNotebook.SetTabLabel (this.FolderContentsPreview, this.label2);
			this.label2.ShowAll ();
			this.hpaned3.Add (this.SyncFolderDetailsNotebook);
			this.vbox2.Add (this.hpaned3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hpaned3]));
			w10.Position = 2;
			// Container child vbox2.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar ();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.vbox2.Add (this.statusbar1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.statusbar1]));
			w11.Position = 3;
			w11.Expand = false;
			w11.Fill = false;
			this.Add (this.vbox2);
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 535;
			this.DefaultHeight = 434;
			this.Show ();
			this.ConnectAction.Activated += new global::System.EventHandler (this.OnConnectActionActivated);
		}
	}
}
